List<Map<int, dynamic>> fourthExamQuestions = [
  {
    1: [
      {
        "q": "",
        "A1": "",
        "A2": "",
        "A3": "",
        "A4": "",
        "a": 2,
        "Level": "I1EQ1",
        "isTF": false,
        "T": "",
      },
      {
        "q": "",
        "A1": "",
        "A2": "",
        "A3": "",
        "A4": "",
        "a": 2,
        "Level": "I2EQ2",
        "isTF": false,
        "T": "",
      },
    ],
    2: [
      {
        "q": "",
        "A1": "",
        "A2": "",
        "A3": "",
        "A4": "",
        "a": 2,
        "Level": "I1MQ1",
        "isTF": false,
        "T": "",
      },
      {
        "q": "",
        "A1": "",
        "A2": "",
        "A3": "",
        "A4": "",
        "a": 2,
        "Level": "I1MQ2",
        "isTF": false,
        "T": "",
      },
    ],
    3: [
      {
        "q": "",
        "A1": "",
        "A2": "",
        "A3": "",
        "A4": "",
        "a": 2,
        "Level": "I1HQ1",
        "isTF": false,
        "T": "",
      },
      {
        "q": "",
        "A1": "",
        "A2": "",
        "A3": "",
        "A4": "",
        "a": 2,
        "Level": "I1HQ2",
        "isTF": false,
        "T": "",
      },
    ],
  },
  {
    1: [
      {
        "q": "",
        "A1": "",
        "A2": "",
        "A3": "",
        "A4": "",
        "a": 2,
        "Level": "I1EQ1",
        "isTF": false,
        "T": "",
      },
      {
        "q": "",
        "A1": "",
        "A2": "",
        "A3": "",
        "A4": "",
        "a": 2,
        "Level": "I2EQ2",
        "isTF": false,
        "T": "",
      },
    ],
    2: [
      {
        "q": "",
        "A1": "",
        "A2": "",
        "A3": "",
        "A4": "",
        "a": 2,
        "Level": "I1MQ1",
        "isTF": false,
        "T": "",
      },
      {
        "q": "",
        "A1": "",
        "A2": "",
        "A3": "",
        "A4": "",
        "a": 2,
        "Level": "I1MQ2",
        "isTF": false,
        "T": "",
      },
    ],
    3: [
      {
        "q": "",
        "A1": "",
        "A2": "",
        "A3": "",
        "A4": "",
        "a": 2,
        "Level": "I1HQ1",
        "isTF": false,
        "T": "",
      },
      {
        "q": "",
        "A1": "",
        "A2": "",
        "A3": "",
        "A4": "",
        "a": 2,
        "Level": "I1HQ2",
        "isTF": false,
        "T": "",
      },
    ],
  },
];

List<int> fourthExamAnswers = [2, 3, 2, 4, 1];
